schema:
  - "http://localhost:5000/graphql"
documents:
  - "api/graphql/**/*.graphql"
generates:
  types/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
